### ISSUE TITLE
export 'Number' was not found

### ISSUE THREAD

**Issue by chaluja7** [mdvorak/resource-router#10]
When building/serving app (with dependency to this resource-router) in development mode (using angular-cli) everything works fine. When moving to production mode, eg. `ng serve --target=production` terrible things happen. 

Warnings during compilation:
WARNING in ./src/main/web/$$_gendir/app/app.module.ngfactory.ts
491:37-51 "export 'Number' (imported as 'import6') was not found in 'angular-resource-router/src/resource-router-module'

WARNING in ./src/main/web/$$_gendir/app/app.module.ngfactory.ts
498:37-51 "export 'Number' (imported as 'import6') was not found in 'angular-resource-router/src/resource-router-module'

WARNING in ./src/main/web/$$_gendir/app/app.module.ngfactory.ts
504:37-51 "export 'Number' (imported as 'import6') was not found in 'angular-resource-router/src/resource-router-module'

Application starts, but doesn't work. Error in browser console: `EXCEPTION: Cannot read property 'MIN_SAFE_INTEGER' of undefined`. Warnings during build are for sure related to given error (eg. Number is undefined).

Not sure, if this is resource-router bug or something else. Weird is, that in development mode everything is ok.

**Comment by mdvorak** [comment]
Reproduced, not sure it actually affects the build.
