### ISSUE TITLE
apiLink causes page reload

### ISSUE THREAD

**Issue by chaluja7** [mdvorak/resource-router#2]
apiLink directive on &lt;a&gt; tag as shown in example app alway causes page reload. It should probably only change location in url bar and serve proper component.

**Comment by mdvorak** [comment]
This will have to wait for #6 and #9, since API for navigation changes with them.

**Comment by mdvorak** [comment]
Closed - added new [resourceLink] directive, old [apiLink] directive remains there with unchanged functionality.

*Replace all apiLink to resourceLink, it should work as expected*
