### ISSUE TITLE
Router supposes that return type is json

### ISSUE THREAD

**Issue by m190** [mdvorak/resource-router#35]
Router supposes that return type is defined or json, that's incorrect assumption! In case of error (e.g. 404) without type header user is getting an exception, instead of correct text processing.

output:
```
Error loading a view router/error from resource http://localhost:4200/... with 999 Routing Error

SyntaxError: Unexpected token H in JSON at position 0
```

response:
```
HTTP/1.1 404 Not Found
X-Powered-By: Express
Access-Control-Allow-Origin: *
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-frame-options: DENY
x-application-context: application:local:8080
transfer-encoding: chunked
date: Wed, 28 Feb 2018 16:12:47 GMT
connection: close
```

During the debug I noticed, that the body is a text (may be formed by Angular):
`Http failure response for http://localhost:4200/...: 404 Not Found`

**Comment by mdvorak** [comment]
Response type must be explicitly set for the view, if it is not JSON. This is usually needed only for custom error pages.

Documentation:
https://mdvorak.github.io/resource-router/components/DefaultErrorComponent.html
